apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weatherapp
  name: weatherapp
  namespace: weather-widget
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weatherapp
      name: weatherapp
    spec:
      containers:
        - env:
            - name: OPEN_WHEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weatherapp-secrets
                  key: weatherApiKey
            - name: UNSPLASH_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: unsplashApiKey
            - name: IP_GEOLOCATION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openWeatherApiKey
                  key: ipGeoApiKey
          image: soreing/weatherapp:prod
          name: weatherapp
          ports:
            - containerPort: 3000
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 54000
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  namespace: weather-widget
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: weatherapp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    acme.cert-manager.io/http01-edit-in-place: "false"
  name: weather-demo-ingress
  namespace: weather-widget
spec:
  rules:
    - host: weather-demo.soreing.cc
      http:
        paths:
          - backend:
              service:
                name: weatherapp-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - weather-demo.soreing.cc
      secretName: weather-demo-ingress-tls
